[workspace]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
name = "ioos_code_lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build_html = { cmd = "cd jupyterbook && jupyter-book build --html" }
jb = { cmd = "python jupyterbook/add_header.py", depends-on=["build_html"] }
linkcheck = { cmd = "jupyter-book build jupyterbook --builder linkcheck" }

[dependencies]
jupyter-book = ">=2.1.6,<3"
