name: Check linkrot

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0

      - name: Build documentation
        run: pixi run linkcheck
